In [1]:
import pandas as pd

### Read markdown in

In [2]:
def read_dataset(file_path: str) -> pd.DataFrame:
    """Reads the dataset from a CSV file and returns a DataFrame.
    
    Args:
        file_path (str): Path to the CSV file.
    """
    return pd.read_csv(file_path)

In [3]:
filename = "feedback_20260101_20260515.csv"

df = read_dataset(filename)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'feedback_20260101_20260515.csv'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         50 non-null     object
 1   path       50 non-null     object
 2   comment    50 non-null     object
 3   createdAt  50 non-null     object
 4   source     50 non-null     object
 5   status     50 non-null     object
 6   helpful    47 non-null     object
 7   contact    0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 3.2+ KB

In [ ]:
df['helpful'].value_counts(dropna=False)

helpful
False    31
True     16
NaN       3
Name: count, dtype: int64

### Replace NaN with text

In [ ]:
df['contact'].fillna('No contact provided', inplace=True)
df['helpful'].fillna("Other", inplace=True)
df.head(n = 22)

,id,path,comment,createdAt,source,status,helpful,contact
0,6a0399f44cec3211b35d1577,/support/weave,[easier-to-understand],2026-05-12T21:21:56.992Z,contextual,pending,False,No contact provided
1,69fd712b3057a9546b8dc9ed,/weave/reference/service-api/opentelemetry/exp...,[update-docs] There's basically nothing here,2026-05-08T05:14:19.082Z,contextual,pending,False,No contact provided
2,69fa5b131e760c915fa95e4f,/models/ref/cli/wandb-login,[something-else-negative] the key generated is...,2026-05-05T21:03:15.834Z,contextual,pending,False,No contact provided
3,69f9f774af3b3d2d31e8bb92,/support/models/articles/how-can-i-delete-my-u...,"[update-docs] There is not button, or it is we...",2026-05-05T13:58:12.307Z,contextual,pending,False,No contact provided
4,69f4e53c97b4ff596d2775e0,/models/track/limits,[easy-to-understand],2026-05-01T17:39:08.874Z,contextual,pending,True,No contact provided
5,69ef295007a3e209ab212d27,/models/runs/resuming,[easier-to-understand] My remove session in vi...,2026-04-27T09:16:00.524Z,contextual,pending,False,No contact provided
6,69eaadd2eb57a71cab262ba6,/platform/app/settings-page/storage,[update-docs] ADD LINKS WHERE TO DELETE DATA I...,2026-04-23T23:40:02.634Z,contextual,pending,False,No contact provided
7,69e8ebf32ef8e36303d175f1,/platform/hosting/hosting-options/self-managed,[up-to-date],2026-04-22T15:40:35.595Z,contextual,pending,True,No contact provided
8,69df7c93bb9786f1b0ee157d,/models/runs/grouping,"[update-docs] Step 4 in ""Remove runs from a gr...",2026-04-15T11:54:59.042Z,contextual,pending,False,No contact provided
9,69d57e7eb9294a6778b71643,/models/ref/python/data-types/table,[worked-as-expected],2026-04-07T22:00:30.332Z,contextual,pending,True,No contact provided
10,69d516f614cefe4d8a28a2b4,/models/integrations/stable-baselines-3,[worked-as-expected],2026-04-07T14:38:46.900Z,contextual,pending,True,No contact provided
11,69d2be034cb316f48f41f037,/models/runs/run-colors,[up-to-date] Go Black pink in portuguese,2026-04-05T19:54:43.307Z,contextual,pending,True,No contact provided
12,69d1620cf167d7b54728102f,/models/registry/download_use_artifact,[easy-to-find],2026-04-04T19:10:04.227Z,contextual,pending,True,No contact provided
13,69cec6bdfa9e20c2d95149e7,/models,[something-else-negative] I think this page is...,2026-04-02T19:42:53.789Z,contextual,pending,False,No contact provided
14,69cbffc8b53cabe8efdc1b05,/,[update-docs],2026-03-31T17:09:28.752Z,contextual,pending,False,No contact provided
15,69c8840adbdf48bbf7f5eb37,/models/sweeps/pause-resume-and-cancel-sweeps,[something-else-positive] Info about early-sto...,2026-03-29T01:44:42.976Z,contextual,pending,True,No contact provided
16,69c2a64cdfb56c3a18f1812f,/platform/hosting/env-vars,[something-else-negative] How do I fetch the s...,2026-03-24T14:57:16.825Z,contextual,pending,False,No contact provided
17,69bc6172352a8e147860ad96,/platform/hosting/iam/org_team_struct,"[something-else-negative] I feel like ""If you ...",2026-03-19T20:49:54.082Z,contextual,pending,False,No contact provided
18,69b944797210ead338b6de27,/models/quickstart,[easy-to-understand],2026-03-17T12:09:29.206Z,contextual,pending,True,No contact provided
19,69b4ed6f6209a5819b9eae4b,/models/app/features/custom-charts/walkthrough,delete,2026-03-14T05:09:03.287Z,code_snippet,pending,Other,No contact provided
20,69b41ad9bec7a00733fdf29d,/platform/launch,[update-docs],2026-03-13T14:10:33.239Z,contextual,pending,False,No contact provided
21,69b418a59c87da408635c041,/platform/app/settings-page/storage,[update-docs] It says delete data interactivel...,2026-03-13T14:01:09.714Z,contextual,pending,False,No contact provided

### Remove entries that were helpful

In [ ]:
# Remove feedback that is not marked as helpful
df[df["helpful"].ne(True) | df["helpful"].eq("Other")]

,id,path,comment,createdAt,source,status,helpful,contact
0,6a0399f44cec3211b35d1577,/support/weave,[easier-to-understand],2026-05-12T21:21:56.992Z,contextual,pending,False,No contact provided
1,69fd712b3057a9546b8dc9ed,/weave/reference/service-api/opentelemetry/exp...,[update-docs] There's basically nothing here,2026-05-08T05:14:19.082Z,contextual,pending,False,No contact provided
2,69fa5b131e760c915fa95e4f,/models/ref/cli/wandb-login,[something-else-negative] the key generated is...,2026-05-05T21:03:15.834Z,contextual,pending,False,No contact provided
3,69f9f774af3b3d2d31e8bb92,/support/models/articles/how-can-i-delete-my-u...,"[update-docs] There is not button, or it is we...",2026-05-05T13:58:12.307Z,contextual,pending,False,No contact provided
5,69ef295007a3e209ab212d27,/models/runs/resuming,[easier-to-understand] My remove session in vi...,2026-04-27T09:16:00.524Z,contextual,pending,False,No contact provided
6,69eaadd2eb57a71cab262ba6,/platform/app/settings-page/storage,[update-docs] ADD LINKS WHERE TO DELETE DATA I...,2026-04-23T23:40:02.634Z,contextual,pending,False,No contact provided
8,69df7c93bb9786f1b0ee157d,/models/runs/grouping,"[update-docs] Step 4 in ""Remove runs from a gr...",2026-04-15T11:54:59.042Z,contextual,pending,False,No contact provided
13,69cec6bdfa9e20c2d95149e7,/models,[something-else-negative] I think this page is...,2026-04-02T19:42:53.789Z,contextual,pending,False,No contact provided
14,69cbffc8b53cabe8efdc1b05,/,[update-docs],2026-03-31T17:09:28.752Z,contextual,pending,False,No contact provided
16,69c2a64cdfb56c3a18f1812f,/platform/hosting/env-vars,[something-else-negative] How do I fetch the s...,2026-03-24T14:57:16.825Z,contextual,pending,False,No contact provided
17,69bc6172352a8e147860ad96,/platform/hosting/iam/org_team_struct,"[something-else-negative] I feel like ""If you ...",2026-03-19T20:49:54.082Z,contextual,pending,False,No contact provided
19,69b4ed6f6209a5819b9eae4b,/models/app/features/custom-charts/walkthrough,delete,2026-03-14T05:09:03.287Z,code_snippet,pending,Other,No contact provided
20,69b41ad9bec7a00733fdf29d,/platform/launch,[update-docs],2026-03-13T14:10:33.239Z,contextual,pending,False,No contact provided
21,69b418a59c87da408635c041,/platform/app/settings-page/storage,[update-docs] It says delete data interactivel...,2026-03-13T14:01:09.714Z,contextual,pending,False,No contact provided
22,69af45bf653fc7e2f97d9a3f,/,[easier-to-find] I want the Python SDK API ref...,2026-03-09T22:12:15.364Z,contextual,pending,False,No contact provided
23,69a9effd237d7798dbe9f180,/platform/hosting/data-security/secure-storage...,[something-else-negative] You should not use a...,2026-03-05T21:05:01.782Z,contextual,pending,False,No contact provided
28,69a985c2c826a3c413d9318e,/models/runs/manage-runs,[something-else-negative] Documentation out of...,2026-03-05T13:31:46.635Z,contextual,pending,False,No contact provided
29,69a79b1b9fa548215e138a07,/,[easier-to-understand] i wanna see at glance w...,2026-03-04T02:38:19.283Z,contextual,pending,False,No contact provided
30,69a19268a9dbf19448b53ff1,/platform/launch,[get-started-faster],2026-02-27T12:47:36.193Z,contextual,pending,False,No contact provided
32,699891f2843e69b2a1ba3f63,/platform/launch,[update-docs],2026-02-20T16:55:14.469Z,contextual,pending,False,No contact provided
33,698d7fcd3e343964fb1998a3,/ko/platform/launch/integration-guides,[update-docs],2026-02-12T07:22:53.694Z,contextual,pending,False,No contact provided
34,698be59f816b5360fed6ede2,/models,[update-docs],2026-02-11T02:12:47.157Z,contextual,pending,False,No contact provided
35,698a0ad3066f474edf74f5eb,/weave/guides/tracking/trace-tree,[something-else-negative] I want to figure out...,2026-02-09T16:26:59.931Z,contextual,pending,False,No contact provided
36,69848e951b066f91d7020ae9,/models/ref/python/custom-charts/line_series,[something-else-negative] there is not picture...,2026-02-05T12:35:33.755Z,contextual,pending,False,No contact provided
39,697d460dcb83135eb8fa4407,/models/ref/python/experiments/artifact,sample_history() doesn't seem to work. Should ...,2026-01-31T00:00:13.209Z,code_snippet,pending,Other,No contact provided
40,697b05ec76d40e03793c741e,/platform/hosting/hosting-options/self-managed,[easier-to-find],2026-01-29T07:02:04.690Z,contextual,pending,False,No contact provided
41,697b04b22525f49928836e25,/models/sweeps/walkthrough,[something-else-negative] You don't show how o...,2026-01-29T06:56:50.433Z,contextual,pending,False,No contact provided
42,6979e02f1147b3837e7ebaf9,/platform/hosting/hosting-options/self-managed,[get-started-faster] Dockerでの簡易的なセルフホストについてもっと...,2026-01-28T10:08:47.039Z,contextual,pending,False,No contact provided
43,69795e4986295cc525718f86,/weave/quickstart,[easier-to-understand] weaveライブラリと、wandbライブラリの...,2026-01-28T00:54:33.143Z,contextual,pending,False,No contact provided
44,697808ec5a97249657c38dd0,/models/ref/python/functions/finish,[get-started-faster] examples,2026-01-27T00:38:04.230Z,contextual,pending,False,No contact provided
45,6977a6e602dea31ef228f476,/platform/launch/create-and-deploy-jobs,[update-docs],2026-01-26T17:39:50.384Z,contextual,pending,False,No contact provided
46,69775a022e19728a4e73854c,/models/ref/python/public-api/api,"Not the code directly, but the mongodb link in...",2026-01-26T12:11:46.602Z,code_snippet,pending,Other,No contact provided
47,6972e8520a13778bf4173b8f,/models/integrations/sagemaker,[something-else-negative] nothing on this doc,2026-01-23T03:17:38.623Z,contextual,pending,False,No contact provided
48,696e9ea1f3ae37376178f36c,/models/ref/cli/wandb-artifact/wandb-artifact-...,[update-docs],2026-01-19T21:14:09.341Z,contextual,pending,False,No contact provided

## Remove contact column

We don't collect contact collumn, so let's get rid of it

In [ ]:
df.drop("contact", axis=1, inplace=True)

In [ ]:
df.columns

Index(['id', 'path', 'comment', 'createdAt', 'source', 'status', 'helpful'], dtype='object')

In [ ]:
df.head()

,id,path,comment,createdAt,source,status,helpful
0,6a0399f44cec3211b35d1577,/support/weave,[easier-to-understand],2026-05-12T21:21:56.992Z,contextual,pending,False
1,69fd712b3057a9546b8dc9ed,/weave/reference/service-api/opentelemetry/exp...,[update-docs] There's basically nothing here,2026-05-08T05:14:19.082Z,contextual,pending,False
2,69fa5b131e760c915fa95e4f,/models/ref/cli/wandb-login,[something-else-negative] the key generated is...,2026-05-05T21:03:15.834Z,contextual,pending,False
3,69f9f774af3b3d2d31e8bb92,/support/models/articles/how-can-i-delete-my-u...,"[update-docs] There is not button, or it is we...",2026-05-05T13:58:12.307Z,contextual,pending,False
4,69f4e53c97b4ff596d2775e0,/models/track/limits,[easy-to-understand],2026-05-01T17:39:08.874Z,contextual,pending,True

---

In [ ]:
# It seems that "code_snippet" in "source" will have "NaN" in "helpful"
df[df['source'] == "code_snippet"].head(n = 15)

,id,path,comment,createdAt,source,status,helpful,contact
19,69b4ed6f6209a5819b9eae4b,/models/app/features/custom-charts/walkthrough,delete,2026-03-14T05:09:03.287Z,code_snippet,pending,NaN,No contact provided
39,697d460dcb83135eb8fa4407,/models/ref/python/experiments/artifact,sample_history() doesn't seem to work. Should ...,2026-01-31T00:00:13.209Z,code_snippet,pending,NaN,No contact provided
46,69775a022e19728a4e73854c,/models/ref/python/public-api/api,"Not the code directly, but the mongodb link in...",2026-01-26T12:11:46.602Z,code_snippet,pending,NaN,No contact provided

## Random statistics

### Reference doc count

In [ ]:
# Checks how many feedback entries are related to the "/ref/" path (reference docs)
df[df['path'].str.contains('models/ref/') | df['path'].str.contains('weave/reference')].head(n = 15)

,id,path,comment,createdAt,source,status,helpful,contact
1,69fd712b3057a9546b8dc9ed,/weave/reference/service-api/opentelemetry/exp...,[update-docs] There's basically nothing here,2026-05-08T05:14:19.082Z,contextual,pending,False,No contact provided
2,69fa5b131e760c915fa95e4f,/models/ref/cli/wandb-login,[something-else-negative] the key generated is...,2026-05-05T21:03:15.834Z,contextual,pending,False,No contact provided
9,69d57e7eb9294a6778b71643,/models/ref/python/data-types/table,[worked-as-expected],2026-04-07T22:00:30.332Z,contextual,pending,True,No contact provided
31,699d3f8e771df2a5341d2182,/models/ref/cli/wandb-launch-sweep,[easy-to-find],2026-02-24T06:05:02.367Z,contextual,pending,True,No contact provided
36,69848e951b066f91d7020ae9,/models/ref/python/custom-charts/line_series,[something-else-negative] there is not picture...,2026-02-05T12:35:33.755Z,contextual,pending,False,No contact provided
39,697d460dcb83135eb8fa4407,/models/ref/python/experiments/artifact,sample_history() doesn't seem to work. Should ...,2026-01-31T00:00:13.209Z,code_snippet,pending,Other,No contact provided
44,697808ec5a97249657c38dd0,/models/ref/python/functions/finish,[get-started-faster] examples,2026-01-27T00:38:04.230Z,contextual,pending,False,No contact provided
46,69775a022e19728a4e73854c,/models/ref/python/public-api/api,"Not the code directly, but the mongodb link in...",2026-01-26T12:11:46.602Z,code_snippet,pending,Other,No contact provided
48,696e9ea1f3ae37376178f36c,/models/ref/cli/wandb-artifact/wandb-artifact-...,[update-docs],2026-01-19T21:14:09.341Z,contextual,pending,False,No contact provided

### Mean, std, percentile, min, max of comments

In [ ]:
# Basic statistics about the length of comments
df['comment'].str.split().str.len().describe()

count    50.00000
mean     10.54000
std      15.30134
min       1.00000
25%       1.00000
50%       2.00000
75%      12.75000
max      74.00000
Name: comment, dtype: float64

In [ ]:
df[df['comment'].str.split().str.len() == 1]

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9      True
10     True
11    False
12     True
13    False
14     True
15    False
16    False
17    False
18     True
19     True
20     True
21    False
22    False
23    False
24     True
25     True
26     True
27     True
28    False
29    False
30     True
31     True
32     True
33     True
34     True
35    False
36    False
37    False
38     True
39    False
40     True
41    False
42    False
43    False
44    False
45     True
46    False
47    False
48     True
49     True
Name: comment, dtype: bool

---
## Scriptify

In [ ]:
# For pipe, we need to return a DataFrame, so we can use assign to modify the column in place
# Keeping this for reference, but it is not used in the final pipeline

# def read_dataset(file_path: str) -> pd.DataFrame:
#     """Reads the dataset from a CSV file and returns a DataFrame.
    
#     Args:
#         file_path (str): Path to the CSV file.
#     """
#     return pd.read_csv(file_path)

# def clean_helpful_nan(df: pd.DataFrame) -> pd.DataFrame:
#     """Replaces NaN values in the 'helpful' column with 'Other'.
    
#     Args:
#         df (pd.DataFrame): The input DataFrame.
        
#     Returns:
#         pd.DataFrame: The modified DataFrame with NaN values replaced.
#     """
#     return df['helpful'].fillna("Other")

# def clean_contact_nan(df: pd.DataFrame) -> pd.DataFrame:
#     """Replaces NaN values in the 'contact' column with 'No contact provided'.
    
#     Args:
#         df (pd.DataFrame): The input DataFrame.
        
#     Returns:
#         pd.DataFrame: The modified DataFrame with NaN values replaced.
#     """
#     return df['contact'].fillna('No contact provided')


# def filter_non_helpful_feedback(df: pd.DataFrame) -> pd.DataFrame:
#     """Filters out feedback entries that are not marked as helpful.
    
#     Args:
#         df (pd.DataFrame): The input DataFrame.
#     Returns:
#         pd.DataFrame: The filtered DataFrame containing only helpful feedback.
#     """
#     return df[df["helpful"].ne(True) | df["helpful"].eq("Other")]

In [ ]:
import pandas as pd

def clean_helpful_nan(df: pd.DataFrame) -> pd.DataFrame:
    """Replace missing values in the 'helpful' column with 'Other'."""
    return df.assign(
        helpful=lambda d: d["helpful"].fillna("Other")
    )


def clean_contact_nan(df: pd.DataFrame) -> pd.DataFrame:
    """Replace missing values in the 'contact' column with a default message."""
    return df.assign(
        contact=lambda d: d["contact"].fillna("No contact provided")
    )


def filter_non_helpful_feedback(df: pd.DataFrame) -> pd.DataFrame:
    """Keep feedback entries that were not marked as helpful."""
    return df.loc[df["helpful"].ne(True)].copy()


def load_feedback_pipeline(raw_df: pd.DataFrame) -> pd.DataFrame:
    """Load, clean, and filter doc feedback."""
    return (
        raw_df
        .pipe(clean_helpful_nan)
        .pipe(clean_contact_nan)
        .pipe(filter_non_helpful_feedback)
    )

In [ ]:
df_raw = df.copy()
df_raw.info()

processed_feedback = load_feedback_pipeline(df_raw)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         50 non-null     object
 1   path       50 non-null     object
 2   comment    50 non-null     object
 3   createdAt  50 non-null     object
 4   source     50 non-null     object
 5   status     50 non-null     object
 6   helpful    47 non-null     object
 7   contact    0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 3.2+ KB

In [ ]:
processed_feedback.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 48
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         34 non-null     object
 1   path       34 non-null     object
 2   comment    34 non-null     object
 3   createdAt  34 non-null     object
 4   source     34 non-null     object
 5   status     34 non-null     object
 6   helpful    34 non-null     object
 7   contact    34 non-null     object
dtypes: object(8)
memory usage: 2.4+ KB

In [ ]:
processed_feedback

,id,path,comment,createdAt,source,status,helpful,contact
0,6a0399f44cec3211b35d1577,/support/weave,[easier-to-understand],2026-05-12T21:21:56.992Z,contextual,pending,False,No contact provided
1,69fd712b3057a9546b8dc9ed,/weave/reference/service-api/opentelemetry/exp...,[update-docs] There's basically nothing here,2026-05-08T05:14:19.082Z,contextual,pending,False,No contact provided
2,69fa5b131e760c915fa95e4f,/models/ref/cli/wandb-login,[something-else-negative] the key generated is...,2026-05-05T21:03:15.834Z,contextual,pending,False,No contact provided
3,69f9f774af3b3d2d31e8bb92,/support/models/articles/how-can-i-delete-my-u...,"[update-docs] There is not button, or it is we...",2026-05-05T13:58:12.307Z,contextual,pending,False,No contact provided
5,69ef295007a3e209ab212d27,/models/runs/resuming,[easier-to-understand] My remove session in vi...,2026-04-27T09:16:00.524Z,contextual,pending,False,No contact provided
6,69eaadd2eb57a71cab262ba6,/platform/app/settings-page/storage,[update-docs] ADD LINKS WHERE TO DELETE DATA I...,2026-04-23T23:40:02.634Z,contextual,pending,False,No contact provided
8,69df7c93bb9786f1b0ee157d,/models/runs/grouping,"[update-docs] Step 4 in ""Remove runs from a gr...",2026-04-15T11:54:59.042Z,contextual,pending,False,No contact provided
13,69cec6bdfa9e20c2d95149e7,/models,[something-else-negative] I think this page is...,2026-04-02T19:42:53.789Z,contextual,pending,False,No contact provided
14,69cbffc8b53cabe8efdc1b05,/,[update-docs],2026-03-31T17:09:28.752Z,contextual,pending,False,No contact provided
16,69c2a64cdfb56c3a18f1812f,/platform/hosting/env-vars,[something-else-negative] How do I fetch the s...,2026-03-24T14:57:16.825Z,contextual,pending,False,No contact provided
17,69bc6172352a8e147860ad96,/platform/hosting/iam/org_team_struct,"[something-else-negative] I feel like ""If you ...",2026-03-19T20:49:54.082Z,contextual,pending,False,No contact provided
19,69b4ed6f6209a5819b9eae4b,/models/app/features/custom-charts/walkthrough,delete,2026-03-14T05:09:03.287Z,code_snippet,pending,Other,No contact provided
20,69b41ad9bec7a00733fdf29d,/platform/launch,[update-docs],2026-03-13T14:10:33.239Z,contextual,pending,False,No contact provided
21,69b418a59c87da408635c041,/platform/app/settings-page/storage,[update-docs] It says delete data interactivel...,2026-03-13T14:01:09.714Z,contextual,pending,False,No contact provided
22,69af45bf653fc7e2f97d9a3f,/,[easier-to-find] I want the Python SDK API ref...,2026-03-09T22:12:15.364Z,contextual,pending,False,No contact provided
23,69a9effd237d7798dbe9f180,/platform/hosting/data-security/secure-storage...,[something-else-negative] You should not use a...,2026-03-05T21:05:01.782Z,contextual,pending,False,No contact provided
28,69a985c2c826a3c413d9318e,/models/runs/manage-runs,[something-else-negative] Documentation out of...,2026-03-05T13:31:46.635Z,contextual,pending,False,No contact provided
29,69a79b1b9fa548215e138a07,/,[easier-to-understand] i wanna see at glance w...,2026-03-04T02:38:19.283Z,contextual,pending,False,No contact provided
30,69a19268a9dbf19448b53ff1,/platform/launch,[get-started-faster],2026-02-27T12:47:36.193Z,contextual,pending,False,No contact provided
32,699891f2843e69b2a1ba3f63,/platform/launch,[update-docs],2026-02-20T16:55:14.469Z,contextual,pending,False,No contact provided
33,698d7fcd3e343964fb1998a3,/ko/platform/launch/integration-guides,[update-docs],2026-02-12T07:22:53.694Z,contextual,pending,False,No contact provided
34,698be59f816b5360fed6ede2,/models,[update-docs],2026-02-11T02:12:47.157Z,contextual,pending,False,No contact provided
35,698a0ad3066f474edf74f5eb,/weave/guides/tracking/trace-tree,[something-else-negative] I want to figure out...,2026-02-09T16:26:59.931Z,contextual,pending,False,No contact provided
36,69848e951b066f91d7020ae9,/models/ref/python/custom-charts/line_series,[something-else-negative] there is not picture...,2026-02-05T12:35:33.755Z,contextual,pending,False,No contact provided
39,697d460dcb83135eb8fa4407,/models/ref/python/experiments/artifact,sample_history() doesn't seem to work. Should ...,2026-01-31T00:00:13.209Z,code_snippet,pending,Other,No contact provided
40,697b05ec76d40e03793c741e,/platform/hosting/hosting-options/self-managed,[easier-to-find],2026-01-29T07:02:04.690Z,contextual,pending,False,No contact provided
41,697b04b22525f49928836e25,/models/sweeps/walkthrough,[something-else-negative] You don't show how o...,2026-01-29T06:56:50.433Z,contextual,pending,False,No contact provided
42,6979e02f1147b3837e7ebaf9,/platform/hosting/hosting-options/self-managed,[get-started-faster] Dockerでの簡易的なセルフホストについてもっと...,2026-01-28T10:08:47.039Z,contextual,pending,False,No contact provided
43,69795e4986295cc525718f86,/weave/quickstart,[easier-to-understand] weaveライブラリと、wandbライブラリの...,2026-01-28T00:54:33.143Z,contextual,pending,False,No contact provided
44,697808ec5a97249657c38dd0,/models/ref/python/functions/finish,[get-started-faster] examples,2026-01-27T00:38:04.230Z,contextual,pending,False,No contact provided
45,6977a6e602dea31ef228f476,/platform/launch/create-and-deploy-jobs,[update-docs],2026-01-26T17:39:50.384Z,contextual,pending,False,No contact provided
46,69775a022e19728a4e73854c,/models/ref/python/public-api/api,"Not the code directly, but the mongodb link in...",2026-01-26T12:11:46.602Z,code_snippet,pending,Other,No contact provided
47,6972e8520a13778bf4173b8f,/models/integrations/sagemaker,[something-else-negative] nothing on this doc,2026-01-23T03:17:38.623Z,contextual,pending,False,No contact provided
48,696e9ea1f3ae37376178f36c,/models/ref/cli/wandb-artifact/wandb-artifact-...,[update-docs],2026-01-19T21:14:09.341Z,contextual,pending,False,No contact provided